name: main - Vai aplicar a pipeline CI/CD e enviar para um servidor de produção

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:

    build:

      runs-on: ubuntu-latest

      steps:

          - uses: actions/checkout@v3

          - uses: actions/setup-node@v2
            with:
              node-version: '16.18.0'

          - run: |
              npm install
              npm run build